services:
  postgres:
    container_name: task_api_postgres_prod
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    container_name: task_api_redis_prod
    volumes:
      - redis_data_prod:/data
      - ./redis/acl.conf:/etc/redis/acl.conf
    command: redis-server --appendonly yes --aclfile /etc/redis/acl.conf
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  api:
    container_name: task_api_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  workers:
    container_name: task_api_workers_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["ndoe", "dist/workers/index.js"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
volumes:
  postgres_data_prod:
  redis_data_prod: