services:
  postgres:
    container_name: task_api_postgres_prod
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    container_name: task_api_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_HOST: postgres

volumes:
  postgres_data_prod: