# multi-stage build

# stage-1
FROM node:20-apline AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# stage-2
FROM node:20-alpine as prod

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY package*.json ./
RUN npm ci --omit=dev

# copying the shell files to the binary executables in the virtual file system of the container
COPY docker/wait-for-pg.sh /usr/local/bin/wait-for-pg
COPY docker/entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/wait-for-pg /usr/local/bin/entrypoint

COPY --from=builder /app/dist ./dist

ENTRYPOINT ["entrypoint"]
CMD [ "node","dist/index.js" ]